[2025-07-01T01:19:15.386+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl scheduled__2025-06-30T00:00:00+00:00 [queued]>
[2025-07-01T01:19:15.391+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl scheduled__2025-06-30T00:00:00+00:00 [queued]>
[2025-07-01T01:19:15.391+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-01T01:19:15.492+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_batch_youtube_etl> on 2025-06-30 00:00:00+00:00
[2025-07-01T01:19:15.495+0000] {standard_task_runner.py:60} INFO - Started process 904 to run task
[2025-07-01T01:19:15.498+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_kpi_daily_batch', 'run_batch_youtube_etl', 'scheduled__2025-06-30T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/youtube_etl_dag.py', '--cfg-path', '/tmp/tmp4xjdjrtq']
[2025-07-01T01:19:15.499+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask run_batch_youtube_etl
[2025-07-01T01:19:15.510+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-01T01:19:15.531+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl scheduled__2025-06-30T00:00:00+00:00 [running]> on host f52b64ea71aa
[2025-07-01T01:19:15.583+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yonatan' AIRFLOW_CTX_DAG_ID='youtube_kpi_daily_batch' AIRFLOW_CTX_TASK_ID='run_batch_youtube_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-30T00:00:00+00:00'
[2025-07-01T01:19:15.603+0000] {logging_mixin.py:188} INFO - Processing channels 1 to 5...
[2025-07-01T01:19:16.094+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/batch_etl.py", line 23, in batch_run
    vid = extract_latest_video_id(ch["channel_id"])
  File "/opt/airflow/scripts/extract_youtube_data.py", line 145, in extract_latest_video_id
    search_response.raise_for_status()
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/youtube/v3/search?key=AIzaSyAFiKSpDVcYBOkCe_3ts37XM3VE3DIduQ0&channelId=UC0ZV6M2THA81QT9hrVWJG3A&part=snippet&order=date&maxResults=1&type=video
[2025-07-01T01:19:16.103+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_kpi_daily_batch, task_id=run_batch_youtube_etl, execution_date=20250630T000000, start_date=20250701T011915, end_date=20250701T011916
[2025-07-01T01:19:16.109+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 22 for task run_batch_youtube_etl (403 Client Error: Forbidden for url: https://www.googleapis.com/youtube/v3/search?key=AIzaSyAFiKSpDVcYBOkCe_3ts37XM3VE3DIduQ0&channelId=UC0ZV6M2THA81QT9hrVWJG3A&part=snippet&order=date&maxResults=1&type=video; 904)
[2025-07-01T01:19:16.135+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-01T01:19:16.145+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T07:02:45.666+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl scheduled__2025-06-30T00:00:00+00:00 [queued]>
[2025-07-01T07:02:45.670+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl scheduled__2025-06-30T00:00:00+00:00 [queued]>
[2025-07-01T07:02:45.670+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-01T07:02:45.779+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_batch_youtube_etl> on 2025-06-30 00:00:00+00:00
[2025-07-01T07:02:45.783+0000] {standard_task_runner.py:60} INFO - Started process 1302 to run task
[2025-07-01T07:02:45.785+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_kpi_daily_batch', 'run_batch_youtube_etl', 'scheduled__2025-06-30T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/youtube_etl_dag.py', '--cfg-path', '/tmp/tmpb80xibmm']
[2025-07-01T07:02:45.786+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask run_batch_youtube_etl
[2025-07-01T07:02:45.796+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-01T07:02:45.814+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl scheduled__2025-06-30T00:00:00+00:00 [running]> on host f52b64ea71aa
[2025-07-01T07:02:45.853+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yonatan' AIRFLOW_CTX_DAG_ID='youtube_kpi_daily_batch' AIRFLOW_CTX_TASK_ID='run_batch_youtube_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-30T00:00:00+00:00'
[2025-07-01T07:02:45.867+0000] {logging_mixin.py:188} INFO - Processing channels 1 to 5...
[2025-07-01T07:02:48.369+0000] {logging_mixin.py:188} INFO - [load_to_postgres_batch] Error: integer out of range
[2025-07-01T07:02:48.370+0000] {logging_mixin.py:188} INFO - Loaded 5 channels and 5 videos.
[2025-07-01T07:02:48.370+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-01T07:02:48.374+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=youtube_kpi_daily_batch, task_id=run_batch_youtube_etl, execution_date=20250630T000000, start_date=20250701T070245, end_date=20250701T070248
[2025-07-01T07:02:48.409+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-01T07:02:48.417+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
